spring:
  application:
      name: EDU-USER
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/online_edu?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  instance:
#    appname: EDU-SERVICE
#    prefer-ip-address: true
server:
  port: 8160
swagger2:
  enable: true
mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  video:
    ak: LTAI5tRSM1DWwECiYCG67EZ7
    sk: gBypdFlTQTerYxXEe95yigBazR8jJU
wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirect_url: http://localhost:8160/api/ucenter/wx/callback